### ISSUE TITLE
code:-504 message:Block or transaction validation failed.

### ISSUE THREAD

**Issue by dungdang95** [x-contract/neo-go-sdk#1]
I use this package to send Neo to one address (TESTNET) but it not work.

     key, _ := neotransaction.DecodeFromWif("L58nL3fUHe9dEqsm*****************")
	tx := neotransaction.CreateContractTransaction()

	tx.AppendOutputByAddrString("AQFvkYJzw2hCJa9ssUxkzNcSQK8BxYZ3uo", neotransaction.AssetNeoID, 1)

	tx.AppendBasicSignWitness(key)

	log.Printf(`Generate contract transaction[%s]`, tx.TXID())
	log.Printf(`  transaction content:`)

	rawtx := tx.RawTransactionString()
	log.Printf(rawtx)

	result := neocliapi.SendRawTransaction("http://seed2.ngd.network:20332", rawtx)
	log.Printf(`Send transaction to neo-cli node result[%v]`, result)

**Comment by terender** [comment]
It seems that you had not append Input in the transaction.

Neo is a UTXO blockchain, so every transaction need at least 1 Input. That Input must be an UTXO(unspent transaction output) from another transaction.
